<?php

/**
 * My Application bootstrap file.
 */
use Nette\Application\Routers\Route;


// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();


// Setup router
if ($container->params['consoleMode']) {
    $application->allowedMethods = FALSE;
    $container->router[] = new Nette\Application\Routers\CliRouter();
} else {
    $container->router[] = $admin = new Nette\Application\Routers\RouteList("Admin");
    $admin[] = new Route('admin/<presenter>/<action>[/<id>]', 'Homepage:default');

    $container->router[] = $front = new Nette\Application\Routers\RouteList("Front");
    
    // Filter articles by category
    $categoriesRouter = array();
    $categories = $container->nette->database->default->table("category");
    foreach ($categories as $category) {	
	$categoriesRouter[\Nette\Utils\Strings::webalize($category["name"])] = $category["category_id"];
    }
    
    $front[] = new Route('kategorie-<category_id>/', array(
	"presenter" => "Homepage",
	"action" => "default",
	"category_id" => array(
	    Route::FILTER_TABLE => $categoriesRouter,
	    Route::FILTER_STRICT => true
	)
    ));

	$front[] = new Route("export.rss", "Rss:export");

	// Articles detail
	$front[] = new Route("<article_id [0-9]+>-<seo>", "Detail:default");

    // Filter articles by author
    $front[] = new Route('autor-<seo>-<author_id [0-9]+>', 'Homepage:default');
    
    // Other
    $front[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
    $front[] = new Route('<presenter>/<action>/', 'Homepage:default');
}


// Configure and run the application!
$container->application->run();
